### ISSUE TITLE
Multiple base dir and baseUri

### ISSUE THREAD

**Issue by prateekrastogi** [yeojz/babel-plugin-transform-assets-import-to-string#6]
Hi,
First of all, thank you for making such an awesome plugin. While testing it with next.js i found that you can not pass multiple multiple base dir and corresponding baseUri i.e. it supports only a single dir import. It would be awesome if it can be able to support multiple basedir and corresponding uri due to general limitations that arise in typical use cases.

**Comment by yeojz** [comment]
Hi @prateekrastogi,

Thanks. Could perhaps give a sample of how you envision you might want to configure it in your use case?

Cheers.

**Comment by prateekrastogi** [comment]
@yeojz , we can pass an array of base directories and their urls in a directories field of options objects. I mean something similar to extensions field in options object, but instead of having an array of strings we will have an array of objects containing base dir and baseuri fields.
Also, I have a doubt that  whether the plugin, at present state, can transform .css extension?

**Comment by yeojz** [comment]
@prateekrastogi do you mean to include css processing? 

If it's just rewriting the url, it should work as intended. The main goal of this plugin was to help with assets rewriting if you're not using a bundler like webpack.

As for multiple urls / base directories, I think it's a good enhancement to have. 
Before going with an implementation, I think the following need to be ironed out:

- will these directories be extension specific?
- should they be in order?
- should we support a global configuration on top of specific configuration?

**Comment by prateekrastogi** [comment]
@yeojz Yeah, just checked it rewriting the url is working fine. I was thinking that it pre-fetches those url's too. 

-  I think the directories should be extension agnostic.

- I can't think of clear use case of why those directories should be in order other than using order for some sort of fallback mechanism for assets. But, I think that some sort of aliasing should be supported to maintain clarity in code for differentiating import from similarly named local directories and cdn dir.

- Again, i think the purpose of global configuration might be for some sort of fallback mechanism or providing a root alias for accessing all the base dir and url, which if provided will definitely require some ordering mechanism for base directories.
