### ISSUE TITLE
Is it possible to only replace the base on production env?

### ISSUE THREAD

**Issue by aviramga** [yeojz/babel-plugin-transform-assets-import-to-string#9]
Hi,

I would like my local dev env to keep serving from my local directory and only when I run the code in production to make the substitute.

Is it possible?

**Comment by yeojz** [comment]
Hi @aviramga,

Yes, you can include it under the env portion of your babelrc instead.. 

Eg:

```json
{
  "plugins": [],
  "env": {
    "production": {
      "plugins": [
        ["transform-assets-import-to-string", {
          "baseDir": "/assets",
          "baseUri": "http://your.cdn.address"
        }]
      ]
    }
  }
}
```

**Comment by aviramga** [comment]
Thanks! But wouldn't  then the import of the image will not work locally?

Import img from "path/to/image"

This is not a valid code without the plugin

**Comment by yeojz** [comment]
The environment is not restricted to just production. You can run a separate configuration for dev.
eg:

You can always set a configuration for development.

```
{
  "env": {
    "development": {
      "plugins": [
        ["transform-assets-import-to-string", {
          "baseDir": "/assets",
          "baseUri": "/assets" // or maybe http://localhost/assets
        }]
      ]
    },
    "production": {
      "plugins": [
        ["transform-assets-import-to-string", {
          "baseDir": "/assets",
          "baseUri": "http://your.cdn.address"
        }]
      ]
    }
  }
}
```

So for local or production, you'll probably be running `NODE_ENV=development` and `NODE_ENV=production` respectively.

**Comment by aviramga** [comment]
Right! Cool stuff! Thanks for the tips!

On Oct 30, 2017 4:33 PM, "Gerald Yeo" <notifications@github.com> wrote:

The environment is not restricted to just production. You can run a
separate configuration for dev.
eg:

You can always set a configuration for development.

{
  "env": {
    "development": {
      "plugins": [
        ["transform-assets-import-to-string", {
          "baseDir": "/assets",
          "baseUri": "/assets" // or maybe http://localhost/assets
        }]
      ]
    },
    "production": {
      "plugins": [
        ["transform-assets-import-to-string", {
          "baseDir": "/assets",
          "baseUri": "http://your.cdn.address"
        }]
      ]
    }
  }
}

So for local or production, you'll probably be running NODE_ENV=development
and NODE_ENV=production respectively.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yeojz/babel-plugin-transform-assets-import-to-string/issues/9#issuecomment-340462375>,
or mute the thread
